var breeds = [
  "Abyssinian",
  "Aegean",
  "American Curl",
  "American Bobtail",
  "American Shorthair",
  "American Wirehair",
  // "Arabian Mau",
  "Australian Mist",
  "Asian",
  "Asian Semi-longhair",
  "Balinese",
  // "Bambino",
  "Bengal",
  "Birman",
  "Bombay",
  "Brazilian Shorthair",
  "British Semi-longhair",
  "British Shorthair",
  "British Longhair",
  "Burmese",
  "Burmilla",
  "California Spangled",
  "Chantilly-Tiffany",
  "Chartreux",
  "Chausie",
  // "Cheetoh",
  "Colorpoint Shorthair",
  "Cornish Rex",
  "Cymric",
  "Manx Longhair",
  "Cyprus",
  "Devon Rex",
  "Donskoy",
  "Don Sphynx",
  "Dragon Li",
  "Dwarf cat",
  "Dwelf",
  "Egyptian Mau",
  "European Shorthair",
  "Exotic Shorthair",
  "German Rex",
  "Havana Brown",
  "Highlander",
  "Himalayan",
  "Colorpoint Persian",
  "Japanese Bobtail",
  "Javanese",
  "Kurilian Bobtail",
  "Khao Manee",
  "Korat",
  // "Korean Bobtail",
  // "Korn Ja",
  // "Kurilian Bobtail",
  // "Kuril Islands Bobtail",
  "LaPerm",
  "Lykoi",
  "Maine Coon",
  "Manx",
  "Mekong Bobtail",
  "Minskin",
  "Munchkin",
  "Nebelung",
  // "Napoleon",
  "Norwegian Forest cat",
  "Ocicat",
  "Ojos Azules",
  "Oregon Rex",
  "Oriental Bicolor",
  "Oriental Shorthair",
  "Oriental Longhair",
  "Persian Cat",
  "Peterbald",
  "Pixie-bob",
  // "Raas",
  "Ragamuffin",
  "Ragdoll",
  "Russian Blue",
  // "Russian White",
  // "Russian Black",
  // "Russian Tabby",
  // "Sam Sawet",
  "Savannah",
  "Scottish Fold",
  "Selkirk Rex",
  "Serengeti",
  "Serrade petit",
  "Siamese",
  "Siberian",
  "Singapura",
  "Snowshoe",
  "Sokoke",
  "Somali",
  "Sphynx",
  "Suphalak",
  "Thai",
  "Thai Lilac",
  "Tonkinese",
  "Toyger",
  "Turkish Angora",
  "Turkish Van",
  "Ukrainian Levkoy"
];

var adjectives = ['Adaptable',
 'Adventurous',
 'Affable',
 'Affectionate',
 'Agreeable',
 'Ambitious',
 'Amiable',
 'Amicable',
 'Amusing',
 'Brave',
 'Bright',
 'Broad-minded',
 'Calm',
 'Careful',
 'Charming',
 'Communicative',
 'Compassionate ',
 'Conscientious',
 'Considerate',
 'Convivial',
 'Courageous',
 'Courteous',
 'Creative',
 'Decisive',
 'Determined',
 'Diligent',
 'Diplomatic',
 'Discreet',
 'Dynamic',
 'Easygoing',
 'Emotional',
 'Energetic',
 'Enthusiastic',
 'Exuberant',
 'Fair-minded',
 'Faithful',
 'Fearless',
 'Forceful',
 'Frank',
 'Friendly',
 'Funny',
 'Generous',
 'Gentle',
 'Good',
 'Gregarious',
 'Hard-working',
 'Helpful',
 'Honest',
 'Humorous',
 'Imaginative',
 'Impartial',
 'Independent',
 'Intellectual',
 'Intelligent',
 'Intuitive',
 'Inventive',
 'Kind',
 'Loving',
 'Loyal',
 'Modest',
 'Neat',
 'Nice',
 'Optimistic',
 'Passionate',
 'Patient',
 'Persistent ',
 'Pioneering',
 'Philosophical',
 'Placid',
 'Plucky',
 'Polite',
 'Powerful',
 'Practical',
 'Pro-active',
 'Quick-witted',
 'Quiet',
 'Rational',
 'Reliable',
 'Reserved',
 'Resourceful',
 'Romantic',
 'Self-confident',
 'Self-disciplined',
 'Sensible',
 'Sensitive',
 'Shy',
 'Sincere',
 'Sociable',
 'Straightforward',
 'Sympathetic',
 'Thoughtful',
 'Tidy',
 'Tough',
 'Unassuming',
 'Understanding',
 'Versatile',
 'Warmhearted',
 'Willing',
 'Witty'
];
